# Generated by Django 6.0.4 on 2026-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('pacial', 'Pago Parcial')], default='pendiente', max_length=15, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
