# Generated by Django 6.0.4 on 2026-05-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_estado_pago_venta_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=15, verbose_name='Estado de Pago'),
        ),
    ]
