# Generated by Django 6.0.4 on 2026-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tasa_bcv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tasa BCV (USD/BS)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_bs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Total (Bolívares)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Total (USD)'),
        ),
    ]
